<?php

use Illuminate\Database\Seeder;

class AnaactesTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
      DB::table('anaactes')->insert([
        [
          'id' => 1,
          'num' => "1.a",
          'abbreviation' => "indiv.",
          'nom' => "analyse individuelle (1 animal)",
          'description' => "strongles gastro-intestinaux",
          'anatype_id' => 1,
          'estSerie' => false,
          'estAnalyse' => true,
          'estTarif' => true,
          'icone_id' => 9,
          'pu_ht' => 14.60,
          'tva_id' => 1,
        ],
        [
          'id' => 2,
          'num' => "1.b",
          'abbreviation' => "mélange de 5",
          'nom' => "analyse de mélange (5 animaux maximum)",
          'description' => "strongles gastro-intestinaux",
          'anatype_id' => 1,
          'estSerie' => false,
          'estAnalyse' => true,
          'estTarif' => true,
          'icone_id' => 9,
          'pu_ht' => 16.90,
          'tva_id' => 1,
        ],
        [
          'id' => 3,
          'num' => "1.c",
          'abbreviation' => "pack 3 anal.",
          'nom' => "pack de 3 échantillons individuels",
          'description' => "strongles gastro-intestinaux",
          'anatype_id' => 1,
          'estSerie' => false,
          'estAnalyse' => true,
          'estTarif' => true,
          'icone_id' => 9,
          'pu_ht' => 35.00,
          'tva_id' => 1,
        ],
        [
          'id' => 4,
          'num' => "1.d",
          'abbreviation' => "suivi annuel",
          'nom' => "pack de suivi annuel (4 envois de 3 échantillons)",
          'description' => "strongles gastro-intestinaux",
          'anatype_id' => 1,
          'estSerie' => true,
          'estAnalyse' => true,
          'estTarif' => true,
          'icone_id' => 9,
          'pu_ht' => 130.00,
          'tva_id' => 1,
        ],
        [
          'id' => 5,
          'num' => "2.a",
          'abbreviation' => "indiv.",
          'nom' => "analyse individuelle (1 animal)",
          'description' => "Analyse coprologique spécifique permettant de compter les oeufs de petite douve en plus de ceux des strongles gastro-intestinaux",
          'anatype_id' => 2,
          'estSerie' => false,
          'estAnalyse' => true,
          'estTarif' => true,
          'icone_id' => 32,
          'pu_ht' => 15.50,
          'tva_id' => 1,
        ],
        [
          'id' => 6,
          'num' => "2.b",
          'abbreviation' => "melange de 5",
          'nom' => "analyse de mélange (5 animaux maximum))",
          'description' => "Analyse coprologique spécifique permettant de compter les oeufs de petite douve en plus de ceux des strongles gastro-intestinaux",
          'anatype_id' => 2,
          'estSerie' => false,
          'estAnalyse' => true,
          'estTarif' => true,
          'icone_id' => 32,
          'pu_ht' => 21.00,
          'tva_id' => 1,
        ],
        [
          'id' => 7,
          'num' => "2.c",
          'abbreviation' => "pack 3 anal.",
          'nom' => "pack de 3 échantillons individuels.",
          'description' => "Analyse coprologique spécifique permettant de compter les oeufs de petite douve en plus de ceux des strongles gastro-intestinaux",
          'anatype_id' => 2,
          'estSerie' => false,
          'estAnalyse' => true,
          'estTarif' => true,
          'icone_id' => 32,
          'pu_ht' => 38.00,
          'tva_id' => 1,
        ],
        [
          'id' => 8,
          'num' => "2.d",
          'abbreviation' => "suivi annuel",
          'nom' => "Pack suivi annuel (4 envois de 3 échantillons par an)",
          'description' => "Analyse coprologique spécifique permettant de compter les oeufs de petite douve en plus de ceux des strongles gastro-intestinaux",
          'anatype_id' => 2,
          'estSerie' => true,
          'estAnalyse' => true,
          'estTarif' => true,
          'icone_id' => 32,
          'pu_ht' => 140.00,
          'tva_id' => 1,
        ],
        [
          'id' => 9,
          'num' => "3.a",
          'abbreviation' => "indiv.",
          'nom' => "analyse individuelle (1 animal)",
          'description' => "recherche de larves de strongles respiratoires",
          'anatype_id' => 3,
          'estSerie' => false,
          'estAnalyse' => true,
          'estTarif' => true,
          'icone_id' => 10,
          'pu_ht' => 10.30,
          'tva_id' => 1,
        ],
        [
          'id' => 10,
          'num' => "3.b",
          'abbreviation' => "mélange de 5",
          'nom' => "analyse de mélange (5 animaux maximum)",
          'description' => "recherche de larves de strongles par le test de Baermann",
          'anatype_id' => 3,
          'estSerie' => false,
          'estAnalyse' => true,
          'estTarif' => true,
          'icone_id' => 10,
          'pu_ht' => 13.00,
          'tva_id' => 1,
        ],
        [
          'id' => 11,
          'num' => "4.a",
          'abbreviation' => "mélange de 5",
          'nom' => "analyse de mélange (5 animaux maximum)",
          'description' => "Analyse coprologique spécifique permettant de compter les oeufs de grande douve et de paramphistome en plus de ceux des strongles gastro-intestinaux",
          'anatype_id' => 4,
          'estSerie' => false,
          'estAnalyse' => true,
          'estTarif' => true,
          'icone_id' => 31,
          'pu_ht' => 19.50,
          'tva_id' => 1,
        ],
        [
          'id' => 12,
          'num' => "5.a",
          'abbreviation' => "mélange",
          'nom' => "analyse de mélange (5 animaux maximum)",
          'description' => "evaluation de la proportion d'oeufs d'Haemonchus par une qPCR",
          'anatype_id' => 5,
          'estSerie' => false,
          'estAnalyse' => true,
          'estTarif' => true,
          'icone_id' => 15,
          'pu_ht' => 49.95,
          'tva_id' => 1,
        ],
        [
          'id' => 13,
          'num' => "6.a",
          'abbreviation' => "2 anal.",
          'nom' => "Analyses coprologiques de mélange avant et après vermifuge (5 à 8 animaux)",
          'description' => "évaluation de l'existence d'une résistance des strongles vis-à-vis des vermifuges",
          'anatype_id' => 6,
          'estSerie' => true,
          'estAnalyse' => true,
          'estTarif' => true,
          'icone_id' => 23,
          'pu_ht' => 50.00,
          'tva_id' => 1,
        ],
        [
          'id' => 14,
          'num' => "7.a",
          'abbreviation' => "kit envoi",
          'nom' => "kit d'echantillonnage pré-affranchi",
          'description' => "pack pour l'envoi des prélèvements avec l'affranchissement",
          'anatype_id' => 7,
          'estSerie' => false,
          'estAnalyse' => false,
          'estTarif' => true,
          'icone_id' => 24,
          'pu_ht' => 9.00,
          'tva_id' => 1,
        ],
        [
          'id' => 15,
          'num' => "1.e",
          'abbreviation' => "pack 3 anal.",
          'nom' => "pack de 3 échantillons de mélanges (5 animaux)",
          'description' => "strongles gastro-intestinaux",
          'anatype_id' => 1,
          'estSerie' => false,
          'estAnalyse' => true,
          'estTarif' => true,
          'icone_id' => 9,
          'pu_ht' => 42.00,
          'tva_id' => 1,
        ],
        [
          'id' => 16,
          'num' => "2.e",
          'abbreviation' => "pack 3 anal.",
          'nom' => "pack de 3 échantillons de mélange (5 animaux)",
          'description' => "Analyse coprologique spécifique permettant de compter les oeufs de petite douve en plus de ceux des strongles gastro-intestinaux",
          'anatype_id' => 2,
          'estSerie' => false,
          'estAnalyse' => true,
          'estTarif' => true,
          'icone_id' => 32,
          'pu_ht' => 45.00,
          'tva_id' => 1,
        ],
        // [
        //   'id' => 5,
        //   'abbreviation' => "INTE",
        //   'nom' => "interprétation des résultats",
        //   'description' => "coût pour la lecture et l'interprétation des résultats",
        //   'estAnalyse' => false,
        //   'anatype_id' => false,
        //   'estTarif' => false,
        //   'icone_id' => 17,
        //   'pu_ht' => 15,
        //   'tva_id' => 1,
        // ],
        // [
        //   'id' => 6,
        //   'abbreviation' => "VISI",
        //   'nom' => "visite d'élevage",
        //   'description' => "coût pour une visite d'élevage parasito (frais de déplacement en supplément)",
        //   'anatype_id' => false,
        //   'estAnalyse' => false,
        //   'estTarif' => false,
        //   'icone_id' => 18,
        //   'pu_ht' => 150,
        //   'tva_id' => 1,
        // ],
        // [
        //   'id' => 7,
        //   'abbreviation' => "DEPL",
        //   'nom' => "frais de déplacement (par km)",
        //   'description' => "frais de déplacement pour une visite au kilometre réel",
        //   'anatype_id' => false,
        //   'estAnalyse' => false,
        //   'estTarif' => false,
        //   'icone_id' => 19,
        //   'pu_ht' => 0.5,
        //   'tva_id' => 1,
        // ],
        // [
        //   'id' => 8,
        //   'abbreviation' => "MELA",
        //   'nom' => "réalisation du mélange",
        //   'description' => "coût supplémentaire pour réaliser un mélange avec des prélèvements individuels",
        //   'anatype_id' => false,
        //   'estAnalyse' => false,
        //   'estTarif' => true,
        //   'icone_id' => 20,
        //   'pu_ht' => 5,
        //   'tva_id' => 1,
        // ],
      ]);
    }
}
