<?php

use Illuminate\Database\Seeder;

class Anaacte_ObservationTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('anaacte_observation')->insert([
          [ 'anaacte_id' => 1, 'observation_id' => 1,],
          [ 'anaacte_id' => 2, 'observation_id' => 1,],
          [ 'anaacte_id' => 3, 'observation_id' => 1,],
          [ 'anaacte_id' => 15, 'observation_id' => 1,],
          [ 'anaacte_id' => 1, 'observation_id' => 1,],
          [ 'anaacte_id' => 2, 'observation_id' => 1,],
          [ 'anaacte_id' => 3, 'observation_id' => 1,],
          [ 'anaacte_id' => 15, 'observation_id' => 1,],
          [ 'anaacte_id' => 5, 'observation_id' => 1,],
          [ 'anaacte_id' => 6, 'observation_id' => 1,],
          [ 'anaacte_id' => 7, 'observation_id' => 1,],
          [ 'anaacte_id' => 16, 'observation_id' => 1,],
          // [ 'anaacte_id' => 9, 'observation_id' => 1,],
          // [ 'anaacte_id' => 10, 'observation_id' => 1,],
          [ 'anaacte_id' => 11, 'observation_id' => 1,],
          [ 'anaacte_id' => 1, 'observation_id' => 2,],
          [ 'anaacte_id' => 2, 'observation_id' => 2,],
          [ 'anaacte_id' => 3, 'observation_id' => 2,],
          [ 'anaacte_id' => 15, 'observation_id' => 2,],
          [ 'anaacte_id' => 1, 'observation_id' => 2,],
          [ 'anaacte_id' => 2, 'observation_id' => 2,],
          [ 'anaacte_id' => 3, 'observation_id' => 2,],
          [ 'anaacte_id' => 15, 'observation_id' => 2,],
          [ 'anaacte_id' => 5, 'observation_id' => 2,],
          [ 'anaacte_id' => 6, 'observation_id' => 2,],
          [ 'anaacte_id' => 7, 'observation_id' => 2,],
          [ 'anaacte_id' => 16, 'observation_id' => 2,],
          [ 'anaacte_id' => 9, 'observation_id' => 2,],
          [ 'anaacte_id' => 10, 'observation_id' => 2,],
          [ 'anaacte_id' => 11, 'observation_id' => 2,],
          [ 'anaacte_id' => 1, 'observation_id' => 3,],
          [ 'anaacte_id' => 2, 'observation_id' => 3,],
          [ 'anaacte_id' => 3, 'observation_id' => 3,],
          [ 'anaacte_id' => 15, 'observation_id' => 3,],
          [ 'anaacte_id' => 1, 'observation_id' => 3,],
          [ 'anaacte_id' => 2, 'observation_id' => 3,],
          [ 'anaacte_id' => 3, 'observation_id' => 3,],
          [ 'anaacte_id' => 15, 'observation_id' => 3,],
          [ 'anaacte_id' => 5, 'observation_id' => 3,],
          [ 'anaacte_id' => 6, 'observation_id' => 3,],
          [ 'anaacte_id' => 7, 'observation_id' => 3,],
          [ 'anaacte_id' => 16, 'observation_id' => 3,],
          [ 'anaacte_id' => 9, 'observation_id' => 3,],
          [ 'anaacte_id' => 10, 'observation_id' => 3,],
          [ 'anaacte_id' => 11, 'observation_id' => 3,],
          [ 'anaacte_id' => 1, 'observation_id' => 4,],
          [ 'anaacte_id' => 2, 'observation_id' => 4,],
          [ 'anaacte_id' => 3, 'observation_id' => 4,],
          [ 'anaacte_id' => 15, 'observation_id' => 4,],
          [ 'anaacte_id' => 1, 'observation_id' => 4,],
          [ 'anaacte_id' => 2, 'observation_id' => 4,],
          [ 'anaacte_id' => 3, 'observation_id' => 4,],
          [ 'anaacte_id' => 15, 'observation_id' => 4,],
          [ 'anaacte_id' => 5, 'observation_id' => 4,],
          [ 'anaacte_id' => 6, 'observation_id' => 4,],
          [ 'anaacte_id' => 7, 'observation_id' => 4,],
          [ 'anaacte_id' => 16, 'observation_id' => 4,],
          [ 'anaacte_id' => 9, 'observation_id' => 4,],
          [ 'anaacte_id' => 10, 'observation_id' => 4,],
          [ 'anaacte_id' => 11, 'observation_id' => 4,],
          [ 'anaacte_id' => 1, 'observation_id' => 5,],
          [ 'anaacte_id' => 2, 'observation_id' => 5,],
          [ 'anaacte_id' => 3, 'observation_id' => 5,],
          [ 'anaacte_id' => 11, 'observation_id' => 5,],
          [ 'anaacte_id' => 1, 'observation_id' => 6,],
          [ 'anaacte_id' => 2, 'observation_id' => 6,],
          [ 'anaacte_id' => 3, 'observation_id' => 6,],
          [ 'anaacte_id' => 15, 'observation_id' => 6,],
          [ 'anaacte_id' => 11, 'observation_id' => 6,],
          [ 'anaacte_id' => 1, 'observation_id' => 7,],
          [ 'anaacte_id' => 11, 'observation_id' => 7,],
          [ 'anaacte_id' => 12, 'observation_id' => 7,],
          [ 'anaacte_id' => 12, 'observation_id' => 7,],
          [ 'anaacte_id' => 12, 'observation_id' => 7,],
          [ 'anaacte_id' => 9, 'observation_id' => 8,],
          [ 'anaacte_id' => 10, 'observation_id' => 8,],
          [ 'anaacte_id' => 9, 'observation_id' => 9,],
          [ 'anaacte_id' => 10, 'observation_id' => 9,],
          [ 'anaacte_id' => 1, 'observation_id' => 10,],
          [ 'anaacte_id' => 2, 'observation_id' => 10,],
          [ 'anaacte_id' => 3, 'observation_id' => 10,],
          [ 'anaacte_id' => 15, 'observation_id' => 10,],
          [ 'anaacte_id' => 12, 'observation_id' => 10,],
          [ 'anaacte_id' => 12, 'observation_id' => 10,],
          [ 'anaacte_id' => 12, 'observation_id' => 10,],
          [ 'anaacte_id' => 12, 'observation_id' => 10,],
          [ 'anaacte_id' => 1, 'observation_id' => 11,],
          [ 'anaacte_id' => 1, 'observation_id' => 11,],
          [ 'anaacte_id' => 5, 'observation_id' => 11,],
          [ 'anaacte_id' => 11, 'observation_id' => 11,],
          [ 'anaacte_id' => 12, 'observation_id' => 11,],
          [ 'anaacte_id' => 12, 'observation_id' => 11,],
          [ 'anaacte_id' => 12, 'observation_id' => 11,],
          [ 'anaacte_id' => 12, 'observation_id' => 11,],
          [ 'anaacte_id' => 12, 'observation_id' => 11,],
          [ 'anaacte_id' => 13, 'observation_id' => 12,],
          [ 'anaacte_id' => 13, 'observation_id' => 12,],
          [ 'anaacte_id' => 13, 'observation_id' => 12,],
          [ 'anaacte_id' => 13, 'observation_id' => 12,],
          [ 'anaacte_id' => 1, 'observation_id' => 13,],
          [ 'anaacte_id' => 1, 'observation_id' => 13,],
          [ 'anaacte_id' => 5, 'observation_id' => 13,],
          [ 'anaacte_id' => 13, 'observation_id' => 13,],
          [ 'anaacte_id' => 15, 'observation_id' => 14,],
          [ 'anaacte_id' => 15, 'observation_id' => 14,],
          [ 'anaacte_id' => 16, 'observation_id' => 14,],
          [ 'anaacte_id' => 13, 'observation_id' => 14,],
          [ 'anaacte_id' => 15, 'observation_id' => 15,],
          [ 'anaacte_id' => 15, 'observation_id' => 15,],
          [ 'anaacte_id' => 16, 'observation_id' => 15,],
          [ 'anaacte_id' => 10, 'observation_id' => 15,],
          [ 'anaacte_id' => 15, 'observation_id' => 16,],
          [ 'anaacte_id' => 15, 'observation_id' => 16,],
          [ 'anaacte_id' => 16, 'observation_id' => 16,],
          // [ 'anaacte_id' => 10, 'observation_id' => 16,],
          [ 'anaacte_id' => 1, 'observation_id' => 17,],
          [ 'anaacte_id' => 15, 'observation_id' => 18,],
          [ 'anaacte_id' => 8, 'observation_id' => 18,],
          [ 'anaacte_id' => 10, 'observation_id' => 18,],
          [ 'anaacte_id' => 15, 'observation_id' => 19,],
          [ 'anaacte_id' => 15, 'observation_id' => 19,],
          [ 'anaacte_id' => 16, 'observation_id' => 19,],
          [ 'anaacte_id' => 10, 'observation_id' => 19,],
          [ 'anaacte_id' => 15, 'observation_id' => 20,],
          [ 'anaacte_id' => 15, 'observation_id' => 20,],
          [ 'anaacte_id' => 16, 'observation_id' => 20,],
          [ 'anaacte_id' => 10, 'observation_id' => 20,],
          [ 'anaacte_id' => 15, 'observation_id' => 21,],
          [ 'anaacte_id' => 15, 'observation_id' => 21,],
          [ 'anaacte_id' => 16, 'observation_id' => 21,],
          [ 'anaacte_id' => 11, 'observation_id' => 21,],
          [ 'anaacte_id' => 1, 'observation_id' => 22,],
          [ 'anaacte_id' => 1, 'observation_id' => 23,],
          [ 'anaacte_id' => 1, 'observation_id' => 23,],
          [ 'anaacte_id' => 5, 'observation_id' => 23,],
          // [ 'anaacte_id' => 9, 'observation_id' => 23,],
          [ 'anaacte_id' => 11, 'observation_id' => 23,],
          [ 'anaacte_id' => 4, 'observation_id' => 24,],
          [ 'anaacte_id' => 4, 'observation_id' => 24,],
          [ 'anaacte_id' => 8, 'observation_id' => 24,],
          [ 'anaacte_id' => 1, 'observation_id' => 25,],
          [ 'anaacte_id' => 2, 'observation_id' => 25,],
          [ 'anaacte_id' => 3, 'observation_id' => 25,],
          [ 'anaacte_id' => 4, 'observation_id' => 25,],
          [ 'anaacte_id' => 15, 'observation_id' => 25,],
          [ 'anaacte_id' => 5, 'observation_id' => 25,],
          [ 'anaacte_id' => 6, 'observation_id' => 25,],
          [ 'anaacte_id' => 7, 'observation_id' => 25,],
          [ 'anaacte_id' => 8, 'observation_id' => 25,],
          [ 'anaacte_id' => 16, 'observation_id' => 25,],
          [ 'anaacte_id' => 12, 'observation_id' => 25,],
          [ 'anaacte_id' => 1, 'observation_id' => 26,],
          [ 'anaacte_id' => 2, 'observation_id' => 26,],
          [ 'anaacte_id' => 3, 'observation_id' => 26,],
          [ 'anaacte_id' => 4, 'observation_id' => 26,],
          [ 'anaacte_id' => 15, 'observation_id' => 26,],
          [ 'anaacte_id' => 12, 'observation_id' => 26,],
          [ 'anaacte_id' => 11, 'observation_id' => 27,],
          [ 'anaacte_id' => 11, 'observation_id' => 27,],
          [ 'anaacte_id' => 11, 'observation_id' => 27,],
          [ 'anaacte_id' => 11, 'observation_id' => 27,],
          [ 'anaacte_id' => 11, 'observation_id' => 28,],
          [ 'anaacte_id' => 11, 'observation_id' => 28,],
          [ 'anaacte_id' => 11, 'observation_id' => 28,],
          [ 'anaacte_id' => 11, 'observation_id' => 28,],
          [ 'anaacte_id' => 5, 'observation_id' => 29,],
          [ 'anaacte_id' => 6, 'observation_id' => 29,],
          [ 'anaacte_id' => 7, 'observation_id' => 29,],
          [ 'anaacte_id' => 8, 'observation_id' => 29,],
          [ 'anaacte_id' => 16, 'observation_id' => 29,],
          [ 'anaacte_id' => 5, 'observation_id' => 29,],
          [ 'anaacte_id' => 6, 'observation_id' => 29,],
          [ 'anaacte_id' => 7, 'observation_id' => 29,],
          [ 'anaacte_id' => 8, 'observation_id' => 29,],
          [ 'anaacte_id' => 16, 'observation_id' => 29,],
          [ 'anaacte_id' => 1, 'observation_id' => 30,],
          [ 'anaacte_id' => 1, 'observation_id' => 31,],
          [ 'anaacte_id' => 1, 'observation_id' => 32,],
          [ 'anaacte_id' => 2, 'observation_id' => 32,],
          [ 'anaacte_id' => 3, 'observation_id' => 34,],
          [ 'anaacte_id' => 7, 'observation_id' => 34,],
          [ 'anaacte_id' => 15, 'observation_id' => 34,],
          [ 'anaacte_id' => 16, 'observation_id' => 34,],

        ]);
    }
}
