<?php

use Illuminate\Database\Seeder;

class AnaactesTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
      DB::table('anaactes')->insert([
        [
          'id' => 1,
          'code' => "SGI",
          'nom' => "analyse individuelle (1 échantillon)",
          'description' => "strongles gastro-intestinaux",
          'anatype_id' => 1,
          'estAnalyse' => true,
          'estTarif' => true,
          'icone_id' => 9,
          'pu_ht' => 14.60,
          'tva_id' => 1,
        ],
        [
          'id' => 2,
          'code' => "SGI",
          'nom' => "analyse de mélange (5 animaux)",
          'description' => "strongles gastro-intestinaux",
          'anatype_id' => 1,
          'estAnalyse' => true,
          'estTarif' => true,
          'icone_id' => 9,
          'pu_ht' => 20.00,
          'tva_id' => 1,
        ],
        [
          'id' => 3,
          'code' => "SGI",
          'nom' => "pack de 3 échantillons individuels",
          'description' => "strongles gastro-intestinaux",
          'anatype_id' => 1,
          'estAnalyse' => true,
          'estTarif' => true,
          'icone_id' => 9,
          'pu_ht' => 35.00,
          'tva_id' => 1,
        ],
        [
          'id' => 4,
          'code' => "SGI",
          'nom' => "pack de suivi annuel (4 envois de 3 échantillons)",
          'description' => "strongles gastro-intestinaux",
          'anatype_id' => 1,
          'estAnalyse' => true,
          'estTarif' => true,
          'icone_id' => 9,
          'pu_ht' => 130.00,
          'tva_id' => 1,
        ],
        [
          'id' => 5,
          'code' => "DICR",
          'nom' => "analyse individuelle",
          'description' => "Analyse coprologique spécifique permettant de compter les oeufs de petite douve en plus de ceux des strongles gastro-intestinaux",
          'anatype_id' => 2,
          'estAnalyse' => true,
          'estTarif' => true,
          'icone_id' => 32,
          'pu_ht' => 15.50,
          'tva_id' => 1,
        ],
        [
          'id' => 6,
          'code' => "DICR",
          'nom' => "analyse de mélange de 5 échantillons",
          'description' => "Analyse coprologique spécifique permettant de compter les oeufs de petite douve en plus de ceux des strongles gastro-intestinaux",
          'anatype_id' => 2,
          'estAnalyse' => true,
          'estTarif' => true,
          'icone_id' => 32,
          'pu_ht' => 21.00,
          'tva_id' => 1,
        ],
        [
          'id' => 7,
          'code' => "DICR",
          'nom' => "pack de 3 échantillons individuels",
          'description' => "Analyse coprologique spécifique permettant de compter les oeufs de petite douve en plus de ceux des strongles gastro-intestinaux",
          'anatype_id' => 2,
          'estAnalyse' => true,
          'estTarif' => true,
          'icone_id' => 32,
          'pu_ht' => 38.00,
          'tva_id' => 1,
        ],
        [
          'id' => 8,
          'code' => "DICR",
          'nom' => "pack de suivi annuel",
          'description' => "recherche de larves de strongles par le test de Baermann",
          'anatype_id' => 2,
          'estAnalyse' => true,
          'estTarif' => true,
          'icone_id' => 32,
          'pu_ht' => 140.00,
          'tva_id' => 1,
        ],
        [
          'id' => 9,
          'code' => "BAER",
          'nom' => "analyse individuelle (1 échantillon)",
          'description' => "recherche de larves de strongles respiratoires",
          'anatype_id' => 3,
          'estAnalyse' => true,
          'estTarif' => true,
          'icone_id' => 10,
          'pu_ht' => 10.30,
          'tva_id' => 1,
        ],
        [
          'id' => 10,
          'code' => "BAER",
          'nom' => "analyse de mélange (mélange de 5 échantillons)",
          'description' => "recherche de larves de strongles par le test de Baermann",
          'anatype_id' => 3,
          'estAnalyse' => true,
          'estTarif' => true,
          'icone_id' => 10,
          'pu_ht' => 18.00,
          'tva_id' => 1,
        ],
        [
          'id' => 11,
          'code' => "FASC",
          'nom' => "analyse de mélange (mélange de 4 échantillons)",
          'description' => "Analyse coprologique spécifique permettant de compter les oeufs de grande douve et de paramphistome en plus de ceux des strongles gastro-intestinaux",
          'anatype_id' => 4,
          'estAnalyse' => true,
          'estTarif' => true,
          'icone_id' => 31,
          'pu_ht' => 19.50,
          'tva_id' => 1,
        ],
        [
          'id' => 12,
          'code' => "HAEM",
          'nom' => "analyse de mélange",
          'description' => "evaluation de la proportion d'oeufs d'Haemonchus par une qPCR",
          'anatype_id' => 5,
          'estAnalyse' => true,
          'estTarif' => true,
          'icone_id' => 15,
          'pu_ht' => 49.95,
          'tva_id' => 1,
        ],
        [
          'id' => 13,
          'code' => "RESI",
          'nom' => "Analyses coprologiques de mélange avant et après vermmifuge",
          'description' => "évaluation de l'existence d'une résistance des strongles vis-à-vis des vermifuges",
          'anatype_id' => 6,
          'estAnalyse' => true,
          'estTarif' => true,
          'icone_id' => 23,
          'pu_ht' => 50.00,
          'tva_id' => 1,
        ],
        [
          'id' => 14,
          'code' => "ENVO",
          'nom' => "kit d'echantillonnage pré-affranchi",
          'description' => "pack pour l'envoi des prélèvements avec l'affranchissement",
          'anatype_id' => null,
          'estAnalyse' => false,
          'estTarif' => true,
          'icone_id' => 24,
          'pu_ht' => 9.00,
          'tva_id' => 2,
        ],
        // [
        //   'id' => 5,
        //   'code' => "INTE",
        //   'nom' => "interprétation des résultats",
        //   'description' => "coût pour la lecture et l'interprétation des résultats",
        //   'estAnalyse' => false,
        //   'anatype_id' => false,
        //   'estTarif' => false,
        //   'icone_id' => 17,
        //   'pu_ht' => 15,
        //   'tva_id' => 1,
        // ],
        // [
        //   'id' => 6,
        //   'code' => "VISI",
        //   'nom' => "visite d'élevage",
        //   'description' => "coût pour une visite d'élevage parasito (frais de déplacement en supplément)",
        //   'anatype_id' => false,
        //   'estAnalyse' => false,
        //   'estTarif' => false,
        //   'icone_id' => 18,
        //   'pu_ht' => 150,
        //   'tva_id' => 1,
        // ],
        // [
        //   'id' => 7,
        //   'code' => "DEPL",
        //   'nom' => "frais de déplacement (par km)",
        //   'description' => "frais de déplacement pour une visite au kilometre réel",
        //   'anatype_id' => false,
        //   'estAnalyse' => false,
        //   'estTarif' => false,
        //   'icone_id' => 19,
        //   'pu_ht' => 0.5,
        //   'tva_id' => 1,
        // ],
        // [
        //   'id' => 8,
        //   'code' => "MELA",
        //   'nom' => "réalisation du mélange",
        //   'description' => "coût supplémentaire pour réaliser un mélange avec des prélèvements individuels",
        //   'anatype_id' => false,
        //   'estAnalyse' => false,
        //   'estTarif' => true,
        //   'icone_id' => 20,
        //   'pu_ht' => 5,
        //   'tva_id' => 1,
        // ],
      ]);
    }
}
