<?php

use Illuminate\Database\Seeder;

class IconesTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::statement('SET FOREIGN_KEY_CHECKS = 0');
        DB::table('icones')->truncate();
        DB::statement('SET FOREIGN_KEY_CHECKS = 1');

        DB::table('icones')->insert([
          ['id' => 1, "nom" => "default.svg", "type" => "divers"],
          ['id' => 2, "nom" => "bv.svg", "type" => "animaux"],
          ['id' => 3, "nom" => "cp.svg", "type" => "animaux"],
          ['id' => 4, "nom" => "cv.svg", "type" => "animaux"],
          ['id' => 5, "nom" => "ov.svg", "type" => "animaux"],
          ['id' => 6, "nom" => "pc.svg", "type" => "animaux"],
          ['id' => 7, "nom" => "pr.svg", "type" => "animaux"],
          ['id' => 8, "nom" => "tout.svg", "type" => "animaux"],
          ['id' => 9, "nom" => "copr.svg", "type" => "analyses"],
          ['id' => 10, "nom" => "baer.svg", "type" => "analyses"],
          ['id' => 11, "nom" => "eleveur.svg", "type" => "personnes"],
          ['id' => 12, "nom" => "labo.svg", "type" => "personnes"],
          ['id' => 13, "nom" => "webmin.svg", "type" => "personnes"],
          ['id' => 14, "nom" => "veto.svg", "type" => "personnes"],
          ['id' => 15, "nom" => "haem.svg", "type" => "analyses"],
          ['id' => 16, "nom" => "pack.svg", "type" => "analyses"],
          ['id' => 17, "nom" => "inte.svg", "type" => "analyses"],
          ['id' => 18, "nom" => "visi.svg", "type" => "analyses"],
          ['id' => 19, "nom" => "depl.svg", "type" => "divers"],
          ['id' => 20, "nom" => "mela.svg", "type" => "analyses"],
          ['id' => 21, "nom" => "users.svg", "type" => "personnes"],
          ['id' => 22, "nom" => "suiv.svg", "type" => "analyses"],
          ['id' => 23, "nom" => "resi.svg", "type" => "analyses"],
          ['id' => 24, "nom" => "envo.svg", "type" => "divers"],
          ['id' => 25, "nom" => "espece.svg", "type" => "animaux"],
          ['id' => 26, "nom" => "ane.svg", "type" => "animaux"],
          ['id' => 27, "nom" => "equides.svg", "type" => "animaux"],
          ['id' => 28, "nom" => "cash.svg", "type" => "divers"],
          ['id' => 29, "nom" => "virement.svg", "type" => "divers"],
          ['id' => 30, "nom" => "cheque.svg", "type" => "divers"],
          ['id' => 31, "nom" => "fasc.svg", "type" => "analyses"],
          ['id' => 32, "nom" => "dicr.svg", "type" => "analyses"],
          ['id' => 33, "nom" => "vl.svg", "type" => "animaux"],
          ['id' => 34, "nom" => "jb.svg", "type" => "animaux"],
          ['id' => 35, "nom" => "acheve.svg", "type" => "divers"],
          ['id' => 36, "nom" => "acte.svg", "type" => "personnes"],
          ['id' => 37, "nom" => "actions.svg", "type" => "personnes"],
          ['id' => 38, "nom" => "ajouter.svg", "type" => "divers"],
          ['id' => 39, "nom" => "analyse.svg", "type" => "analyses"],
          ['id' => 40, "nom" => "analyse_nouvelle.svg", "type" => "analyses"],
          ['id' => 41, "nom" => "blog.svg", "type" => "divers"],
          ['id' => 42, "nom" => "cas_equides.svg", "type" => "animaux"],
          ['id' => 43, "nom" => "choisir.svg", "type" => "divers"],
          ['id' => 44, "nom" => "contact.svg", "type" => "personnes"],
          ['id' => 45, "nom" => "cv_rond.svg", "type" => "animaux"],
          ['id' => 46, "nom" => "date.svg", "type" => "divers"],
          ['id' => 47, "nom" => "demandes.svg", "type" => "analyses"],
          ['id' => 48, "nom" => "eleveur_rond.svg", "type" => "personnes"],
          ['id' => 49, "nom" => "email.svg", "type" => "divers"],
          ['id' => 50, "nom" => "enpratique.svg", "type" => "divers"],
          ['id' => 51, "nom" => "entomo.svg", "type" => "divers"],
          ['id' => 52, "nom" => "entravaux.svg", "type" => "divers"],
          ['id' => 53, "nom" => "envoye.svg", "type" => "divers"],
          ['id' => 54, "nom" => "especes.svg", "type" => "animaux"],
          ['id' => 55, "nom" => "exclusions.svg", "type" => "analyses"],
          ['id' => 56, "nom" => "factures.svg", "type" => "divers"],
          ['id' => 57, "nom" => "felicitations.svg", "type" => "divers"],
          ['id' => 58, "nom" => "fibl-logo.svg", "type" => "divers"],
          ['id' => 59, "nom" => "fleche_gauche.svg", "type" => "divers"],
          ['id' => 60, "nom" => "formulaire_ligne.svg", "type" => "analyses"],
          ['id' => 61, "nom" => "formulaire_vierge.svg", "type" => "analyses"],
          ['id' => 62, "nom" => "horaires.svg", "type" => "divers"],
          ['id' => 63, "nom" => "icones.svg", "type" => "divers"],
          ['id' => 64, "nom" => "inacheve.svg", "type" => "divers"],
          ['id' => 65, "nom" => "inconnu.svg", "type" => "divers"],
          ['id' => 66, "nom" => "info_blanc.svg", "type" => "divers"],
          ['id' => 67, "nom" => "infoslegales.svg", "type" => "divers"],
          ['id' => 68, "nom" => "interpreter.svg", "type" => "analyses"],
          ['id' => 69, "nom" => "microscope.svg", "type" => "analyses"],
          ['id' => 70, "nom" => "modifier.svg", "type" => "divers"],
          ['id' => 71, "nom" => "nouveau.svg", "type" => "personnes"],
          ['id' => 72, "nom" => "observation_add.svg", "type" => "divers"],
          ['id' => 73, "nom" => "observations.svg", "type" => "divers"],
          ['id' => 74, "nom" => "oeuf.jpg", "type" => "analyses"],
          ['id' => 75, "nom" => "oeuf.jpg.webp", "type" => "analyses"],
          ['id' => 76, "nom" => "pack-envoi.svg", "type" => "analyses"],
          ['id' => 77, "nom" => "pack-envoi-vide.svg", "type" => "analyses"],
          ['id' => 78, "nom" => "parasitisme.svg", "type" => "animaux"],
          ['id' => 79, "nom" => "pas_fini.svg", "type" => "divers"],
          ['id' => 80, "nom" => "prelevement.svg", "type" => "analyses"],
          ['id' => 81, "nom" => "prelever.svg", "type" => "analyses"],
          ['id' => 82, "nom" => "question.svg", "type" => "personnes"],
          ['id' => 83, "nom" => "question2.svg", "type" => "personnes"],
          ['id' => 84, "nom" => "saisie.svg", "type" => "analyses"],
          ['id' => 85, "nom" => "saisie_faite.svg", "type" => "analyses"],
          ['id' => 86, "nom" => "saisie_signee.svg", "type" => "analyses"],
          ['id' => 87, "nom" => "saisie_non_faite.svg", "type" => "analyses"],
          ['id' => 88, "nom" => "serie.svg", "type" => "analyses"],
          ['id' => 89, "nom" => "signature.svg", "type" => "divers"],
          ['id' => 90, "nom" => "situation.svg", "type" => "divers"],
          ['id' => 91, "nom" => "telephone.svg", "type" => "divers"],
          ['id' => 92, "nom" => "veto_rond.svg", "type" => "personnes"],
          ['id' => 93, "nom" => "why.svg", "type" => "divers"],
          ['id' => 94, "nom" => "fast.svg", "type" => "divers"],
          ['id' => 95, "nom" => "marcheur.svg", "type" => "personnes"],
          ['id' => 96, "nom" => "enveloppe.svg", "type" => "divers"],
        ]);
    }
}
