<?php

use Illuminate\Database\Seeder;

class IconesTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::statement('SET FOREIGN_KEY_CHECKS = 0');
        DB::table('icones')->truncate();
        DB::statement('SET FOREIGN_KEY_CHECKS = 1');

        DB::table('icones')->insert([
          ['id' => 1, "nom" => "default.svg"],
          ['id' => 2, "nom" => "bv.svg"],
          ['id' => 3, "nom" => "cp.svg"],
          ['id' => 4, "nom" => "cv.svg"],
          ['id' => 5, "nom" => "ov.svg"],
          ['id' => 6, "nom" => "pc.svg"],
          ['id' => 7, "nom" => "pr.svg"],
          ['id' => 8, "nom" => "tout.svg"],
          ['id' => 9, "nom" => "copr.svg"],
          ['id' => 10, "nom" => "baer.svg"],
          ['id' => 11, "nom" => "eleveur.svg"],
          ['id' => 12, "nom" => "labo.svg"],
          ['id' => 13, "nom" => "webmin.svg"],
          ['id' => 14, "nom" => "veto.svg"],
          ['id' => 15, "nom" => "haem.svg"],
          ['id' => 16, "nom" => "pack.svg"],
          ['id' => 17, "nom" => "inte.svg"],
          ['id' => 18, "nom" => "visi.svg"],
          ['id' => 19, "nom" => "depl.svg"],
          ['id' => 20, "nom" => "mela.svg"],
          ['id' => 21, "nom" => "users.svg"],
          ['id' => 22, "nom" => "suiv.svg"],
          ['id' => 23, "nom" => "resi.svg"],
          ['id' => 24, "nom" => "envo.svg"],
          ['id' => 25, "nom" => "espece.svg"],
          ['id' => 26, "nom" => "ane.svg"],
          ['id' => 27, "nom" => "equides.svg"],
          ['id' => 28, "nom" => "cash.svg"],
          ['id' => 29, "nom" => "virement.svg"],
          ['id' => 30, "nom" => "cheque.svg"],
          ['id' => 31, "nom" => "fasc.svg"],
          ['id' => 32, "nom" => "dicr.svg"],
          ['id' => 33, "nom" => "vl.svg"],
          ['id' => 34, "nom" => "jb.svg"],
          ['id' => 35, "nom" => "acheve.svg"],
          ['id' => 36, "nom" => "acte.svg"],
          ['id' => 37, "nom" => "actions.svg"],
          ['id' => 38, "nom" => "ajouter.svg"],
          ['id' => 39, "nom" => "analyse.svg"],
          ['id' => 40, "nom" => "analyse_nouvelle.svg"],
          ['id' => 41, "nom" => "blog.svg"],
          ['id' => 42, "nom" => "cas_equides.svg"],
          ['id' => 43, "nom" => "choisir.svg"],
          ['id' => 44, "nom" => "contact.svg"],
          ['id' => 45, "nom" => "cv_rond.svg"],
          ['id' => 46, "nom" => "date.svg"],
          ['id' => 47, "nom" => "demandes.svg"],
          ['id' => 48, "nom" => "eleveur_rond.svg"],
          ['id' => 49, "nom" => "email.svg"],
          ['id' => 50, "nom" => "enpratique.svg"],
          ['id' => 51, "nom" => "entomo.svg"],
          ['id' => 52, "nom" => "entravaux.svg"],
          ['id' => 53, "nom" => "envoye.svg"],
          ['id' => 54, "nom" => "especes.svg"],
          ['id' => 55, "nom" => "exclusions.svg"],
          ['id' => 56, "nom" => "factures.svg"],
          ['id' => 57, "nom" => "felicitations.svg"],
          ['id' => 58, "nom" => "fibl-logo.svg"],
          ['id' => 59, "nom" => "fleche_gauche.svg"],
          ['id' => 60, "nom" => "formulaire_ligne.svg"],
          ['id' => 61, "nom" => "formulaire_vierge.svg"],
          ['id' => 62, "nom" => "horaires.svg"],
          ['id' => 63, "nom" => "icones.svg"],
          ['id' => 64, "nom" => "inacheve.svg"],
          ['id' => 65, "nom" => "inconnu.svg"],
          ['id' => 66, "nom" => "info_blanc.svg"],
          ['id' => 67, "nom" => "infoslegales.svg"],
          ['id' => 68, "nom" => "interpreter.svg"],
          ['id' => 69, "nom" => "microscope.svg"],
          ['id' => 70, "nom" => "modifier.svg"],
          ['id' => 71, "nom" => "nouveau.svg"],
          ['id' => 72, "nom" => "observation_add.svg"],
          ['id' => 73, "nom" => "observations.svg"],
          ['id' => 74, "nom" => "oeuf.jpg"],
          ['id' => 75, "nom" => "oeuf.jpg.webp"],
          ['id' => 76, "nom" => "pack-envoi.svg"],
          ['id' => 77, "nom" => "pack-envoi-vide.svg"],
          ['id' => 78, "nom" => "parasitisme.svg"],
          ['id' => 79, "nom" => "pas_fini.svg"],
          ['id' => 80, "nom" => "prelevement.svg"],
          ['id' => 81, "nom" => "prelever.svg"],
          ['id' => 82, "nom" => "question.svg"],
          ['id' => 83, "nom" => "question2.svg"],
          ['id' => 84, "nom" => "saisie.svg"],
          ['id' => 85, "nom" => "saisie_faite.svg"],
          ['id' => 86, "nom" => "saisie_faite_signee.svg"],
          ['id' => 87, "nom" => "saisie_non_faite.svg"],
          ['id' => 88, "nom" => "serie.svg"],
          ['id' => 89, "nom" => "signature.svg"],
          ['id' => 90, "nom" => "situation.svg"],
          ['id' => 91, "nom" => "telephone.svg"],
          ['id' => 92, "nom" => "veto_rond.svg"],
          ['id' => 93, "nom" => "why.svg"],
        ]);
    }
}
